const CartActionTypes = {
    TOOGGLE_CART_HIDDEN : 'TOOGGLE_CART_HIDDEN',
    ADD_ITEM:'ADD_ITEM',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    REMOVE_ITEM: 'REMOVE_ITEM'
}

export default CartActionTypes;